const {
  VITE_API_BASE_URL,
  VITE_NUMBER_OF_JOKES,
  VITE_STORE_KEY_FAVORITES,
  VITE_STORE_KEY_NEW_JOKES,
  VITE_STORE_KEY_JOKES_LAST_FETCH_Date,
  VITE_STORE_KEY_JOKE_TYPE,
} = import.meta.env

export const appConfig = {
  API_BASE_URL:
    VITE_API_BASE_URL || 'https://official-joke-api.appspot.com/jokes',
  NUMBER_OF_JOKES: VITE_NUMBER_OF_JOKES || 10,
  STORE_KEY_FAVORITES: VITE_STORE_KEY_FAVORITES || 'favorite_jokes',
  STORE_KEY_NEW_JOKES: VITE_STORE_KEY_NEW_JOKES || 'new_jokes',
  STORE_KEY_JOKES_LAST_FETCH_DATE:
    VITE_STORE_KEY_JOKES_LAST_FETCH_Date || 'jokes_fetched_last_date',
  STORE_KEY_JOKE_TYPE: VITE_STORE_KEY_JOKE_TYPE || 'joke_type',
} as const
